"""Markdown report export."""
from __future__ import annotations
from datetime import datetime


def export_markdown(findings: list[dict], project_name: str = "Penetration Test") -> str:
    """Generate a professional Markdown pentest report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Count by severity
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info").lower()
        counts[sev] = counts.get(sev, 0) + 1

    lines = [
        f"# {project_name} — Penetration Test Report",
        f"",
        f"**Generated:** {now}  ",
        f"**Tool:** RedTeam AI v0.1.0  ",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"This report documents findings from an authorized penetration test.",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {counts['critical']} |",
        f"| 🟠 High     | {counts['high']} |",
        f"| 🟡 Medium   | {counts['medium']} |",
        f"| 🟢 Low      | {counts['low']} |",
        f"| 🔵 Info     | {counts['info']} |",
        f"| **Total**   | **{len(findings)}** |",
        f"",
        f"---",
        f"",
        f"## Findings",
        f"",
    ]

    if not findings:
        lines.append("*No findings recorded.*")
    else:
        # Sort: critical first
        order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        sorted_findings = sorted(findings, key=lambda f: order.get(f.get("severity", "info"), 5))

        for i, finding in enumerate(sorted_findings, 1):
            sev = finding.get("severity", "info").upper()
            title = finding.get("title", "Untitled Finding")
            desc = finding.get("description", "No description provided.")
            remediation = finding.get("remediation", "No remediation specified.")
            cvss = finding.get("cvss_score", "")
            cves = finding.get("cve_ids", "")
            status = finding.get("status", "open")

            lines += [
                f"### {i}. [{sev}] {title}",
                f"",
                f"**Status:** {status.title()}  ",
            ]
            if cvss:
                lines.append(f"**CVSS Score:** {cvss}  ")
            if cves:
                lines.append(f"**CVE IDs:** {cves}  ")
            lines += [
                f"",
                f"**Description:**",
                f"",
                f"{desc}",
                f"",
                f"**Remediation:**",
                f"",
                f"{remediation}",
                f"",
                f"---",
                f"",
            ]

    lines += [
        f"## Disclaimer",
        f"",
        f"This assessment was performed on authorized systems only. All findings should be verified",
        f"before remediation. RedTeam AI is a tool to assist — not replace — professional judgment.",
        f"",
        f"*Report generated by [RedTeam AI](https://github.com/your-org/redteamai)*",
    ]

    return "\n".join(lines)
